mode: MPIIGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIGaze.h5
model:
  name: googlenet
train:
  batch_size: 32
  optimizer: sgd
  base_lr: 0.01
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001
  loss: L2
  seed: 0
  test_id: -1
  val_ratio: 0.1
  output_dir: experiments/mpiigaze/googlenet/exp04
  log_period: 100
  checkpoint_period: 10
  use_tensorboard: True
  train_dataloader:
    num_workers: 4
    drop_last: True
    pin_memory: False
  val_dataloader:
    num_workers: 4
    pin_memory: False
scheduler:
  epochs: 15
  type: onecycle
  max_lr: 0.015
  pct_start: 0.3
  three_phase: True
  div_factor: 2
  final_div_factor: 4
cudnn:
  benchmark: True
  deterministic: False
